version: '2'
services:
  airlines:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
      - .:/usr/app/client
      - /usr/app/client/node_modules
    ports:
      - "5000:5001"
    environment:
      - cat .env