version: "2"

services:
  airlines:
    build:
      context: .
      dockerfile: Dockerfile
    image: airlines-${BRANCH_NAME}:1.0.${BUILD_NUMBER}
    container_name: airlines-${BRANCH_NAME}
    environment:
      - ${MONGO_URI}="mongodb+srv://stolar:reklamacija1@cluster0-rezzp.mongodb.net/test?retryWrites=true&w=majority"
    restart: always
    ports:
      - "${PORT_NUMBER}:5000"
