version: "2"
services:
  airlines:
    build:
      context: .
      dockerfile: Dockerfile
    image: airlines-${BRANCH_NAME}:1.0.${BUILD_NUMBER}
    container_name: airlines-${BRANCH_NAME}
    ports:
      - "5000:5001"
    environment:
      - cat .env
    restart: always
